#!/bin/bash
#PBS -l nodes=1:ppn=1,walltime=01:00:00
#PBS -N app-surface-data-resample
#PBS -l vmem=16gb
#PBS -V

# set -e

[ -z "$FREESURFER_LICENSE" ] && echo "Please set FREESURFER_LICENSE in .bashrc" && exit 1;
echo $FREESURFER_LICENSE > license.txt

echo "resampling surface data"

time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/freesurfer:7.2.0 ./convert-template-surfaces.sh

time singularity exec -e -B `pwd`/license.txt:/usr/local/freesurfer/license.txt docker://brainlife/connectome_workbench:1.5.0 ./resample-surface.sh
